### PR TITLE
Update docs after PSI shutdown

### PR DESCRIPTION
**Pull request by majamassarini**

### CODE REVIEW

**Review by mfocko — APPROVED** [review]
Have you managed to verify that it works on `prod` too? Cause the ticket against IT for allowing `copr.fedorainfracloud.org` is still in progress :eyes:

**Comment by majamassarini** [comment]
> Have you managed to verify that it works on `prod` too? Cause the ticket against IT for allowing `copr.fedorainfracloud.org` is still in progress 👀

yes, I ran tests in preprod and prod and they both seems to be working. I think the reason is that we are just making html requests out of the validation project.

**Comment by mfocko** [comment]
interesting

**Comment by majamassarini** [comment]
Closing this and opening a new one.

**Pull request closed without merging**
